### PR TITLE
fix(legacy): prevent removal of default commissioning scripts from machine details form

### LINKED ISSUE #1668: Builtin commissioning scripts should be unable to be deselected on the node-details page
Bug originally filed by ltrager at https://bugs.launchpad.net/bugs/1896174

LP:1892238 solved this for the nodes listing page but when I use the commissioning form on the node details page I can still deselect builtin commissioning scripts.

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- The third-party ngTagsInput library doesn't allow disabling a subset of tags, so I've used a terrible css hack to prevent default commissioning scripts from being removed in the legacy form.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to the machine details page of a machine that can be commissioned and open the Commission form
- Check that the default commissioning scripts show up by default, they cannot be removed and they are sorted alphanumerically
- Add a non-default script and check that you can then remove it
- Open the Test action form and check that it has remained unchanged

## Fixes

Fixes #1668

### CODE REVIEW

File: legacy/src/app/directives/script_select.js [hunk 1]
```diff
@@ -17,6 +17,12 @@ function filterScriptsByParam(scripts, param) {
   });
 }
 
+const sortScripts = (a, b) => {
```
Comment (squidsoup) [inline legacy/src/app/directives/script_select.js:20]: This is fine (given we're killing this soon), but just so you know there's a nicer way to do this today with [localCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Browser_compatibility):

```
['qux', 'bar', 'foo'].sort((a, b) => a.localeCompare(b))
> ["bar", "foo", "qux"]
```

**Review by squidsoup — APPROVED** [review]
+1 for filthy css hack

File: legacy/src/app/directives/script_select.js (hunk 1 above)
Comment (Caleb-Ellis) [reply legacy/src/app/directives/script_select.js:20]: I'll remember for next time!
