### PR TITLE
fix(ui): round free storage values down in machine details

### LINKED ISSUE #2396: Storage input validation unhelpful for rounded values
In the new storage forms when entering sizes there are sometimes rounding issues that result in errors like the following:

Screen Shot 2021-03-16 at 2 29 03 pm

### LINKED ISSUE #2612: Default logical volume size too big in UI
Bug originally filed by ltrager at https://bugs.launchpad.net/bugs/1927559

I used the UI to create an LVM group across two disks. I then used the UI to create a logical volume in the LVM group. The default volume size is too big. The UI knows this and doesn't allow me to create the volume. If I reduce the size by .1 I can create the logical volume.

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Updated formatBytes to be able to change rounding direction. Removed toPrecision which was a bit
too unreliable and inconsistent.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to the storage tab of a Ready or Allocated machine (e.g. /MAAS/r/machine/bx7taq/storage on bolla)
- Create a partition of size 1001MB
- Check that the free space correctly rounds down
- Open the add partition form again and check that it auto-fills with the rounded-down value
- Run the same tests but with logical volumes (create partition -> create volume group -> add logical volume)

## Fixes

Fixes #2396 
Fixes #2612

### CODE REVIEW

File: ui/src/app/utils/formatBytes.ts [hunk 1]
```diff
@@ -3,25 +3,32 @@ export type Byte = { value: number; unit: string };
...
- * @param {boolean} config.convertTo - the unit to convert to
- * @param {number} config.precision - significant figures of returned value
- * @returns {Byte} formatted value and byte unit object
+ * @param value - the value in the supplied byte unit
+ * @param unit - the byte unit, e.g. "KB", "TB"
+ * @param config - config object
+ * @param config.binary - whether formatting should be done in base 10 or 2
+ * @param config.convertTo - the unit to convert to
+ * @param config.decimals - the decimal places to show, if not a whole number
+ * @param config.roundDirection - whether to round the value up or down
```
Comment (huwshimi) [inline ui/src/app/utils/formatBytes.ts:19]: I think this should be `roundFunc`.

**Review by huwshimi — APPROVED** [review]
Looks good. We also need to use this in the pod compose forms (as a followup).

File: ui/src/app/utils/formatBytes.ts (hunk 1 above)
Comment (Caleb-Ellis) [reply ui/src/app/utils/formatBytes.ts]: Oops you're right!
