### PR TITLE
fix(ui): correctly type machine parameters

### LINKED ISSUE #2421: Error viewing pod without ip addresses
Viewing http://bolla.internal:5240/MAAS/r/kvm/190/project gives `TypeError: Cannot read property 'reduce' of undefined` from 

```typescript
IPColumn
src/app/kvm/views/KVMDetails/LxdProject/ProjectVMs/VMsTable/IPColumn/IPColumn.tsx:23
  20 |   return <Spinner />;
  21 | }
  22 | 
> 23 | const ips = machine.ip_addresses.reduce<string[]>((ips, { ip }) => {
     | ^  24 |   if (
  25 |     (version === 4 && IPV4_REGEX.test(ip)) ||
  26 |     (version === 6 && !IPV4_REGEX.test(ip))
```

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Updated `BaseMachine` type to correctly reflect what parameters are optional, e.g. if no boot interface is set a few things are missing.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- In a LXD pod, compose a new machine or go to the machine details page of an existing one that can have its network edited
- Remove all of its interfaces
- Go to the project details page of the pod and check that the browser doesn't crash

## Fixes

Fixes #2421

### CODE REVIEW

File: ui/src/app/store/machine/types.ts [hunk 1]
```diff
@@ -249,15 +249,16 @@ export type BaseMachine = BaseNode & {
   pool: ModelRef;
   power_state: PowerState;
   power_type: string;
-  pxe_mac_vendor: string;
-  pxe_mac: string;
+  pxe_mac_vendor?: string;
+  pxe_mac?: string;
   spaces: string[];
   sriov_support: boolean;
+  status_message: string;
```
Comment (Caleb-Ellis) [inline ui/src/app/store/machine/types.ts:256]: This was also missing - it's the secondary row in the machine list's status column

**Review by huwshimi — APPROVED** [review]
Nice.
