### PR TITLE
fix(ui): re-add KVM storage pool sorting with resources endpoint

### LINKED ISSUE #3232: Re-add default pod storage pool sorting
Switching the api endpoint from `pod.storage_pools` to `pod.resources.storage_pools` meant that we lost the pool `id` and therefore the ability to sort by default id. Once the API is updated ([LP bug](https://bugs.launchpad.net/maas/+bug/1949681)) we should re-add this functionality.

EDIT: cluster storage pools can have multiple ids, so this means we can only sort by id for pod storage pools

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Re-implemented KVM storage pool sorting using `pod.resources.storage_pools` as opposed to `pod.storage_pools` 
- Removed `pod.getSortedPools` selector as we want sorting to work across pods and clusters

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to the LXD KVM list and hover over the storage column and check that single hosts show a "default" pool but clusters do not
- Go to the Resources tab of a LXD single host and check that the storage label says "Sorted by id, default first"
- Go to the Resources tab of a LXD cluster and check that the storage label says "Sorted by name"
- A proper QA will require you to set up a LXD host locally and adding multiple pools to it, otherwise you can use test factories in `KVMStorageCards`, `PoolSelect` and `StoragePopover` to check that the pools are sorting correctly.

## Fixes

Fixes #3232

### CODE REVIEW

File: ui/src/app/kvm/components/KVMStorageCards/KVMStorageCards.tsx [hunk 1]
```diff
@@ -5,32 +5,42 @@ import pluralize from "pluralize";
...
   return (
     <>
-      <h4 className="u-sv1">Storage</h4>
+      <h4 className="u-sv1">
+        Storage&nbsp;
+        <span
+          className="p-text--paragraph u-text--light"
+          data-test="sort-label"
+        >
+          {defaultPoolId ? "(Sorted by id, default first)" : "(Sorted by name)"}
```
Comment (huwshimi) [inline ui/src/app/kvm/components/KVMStorageCards/KVMStorageCards.tsx:41]: This might be a bit pedantic but do you think these should have a lower case "s" in "sorted"?

File: ui/src/app/kvm/components/StorageColumn/StoragePopover/StoragePopover.tsx [hunk 2]
```diff
@@ -4,20 +4,24 @@ import { Fragment } from "react";
...
-const StoragePopover = ({ children, pools }: Props): JSX.Element => {
-  const poolsArray = Object.entries<KVMStoragePoolResource>(pools);
-  const showOthers = poolsArray.some((pool) => pool[1].allocated_other !== 0);
+const StoragePopover = ({
+  children,
+  defaultPoolId,
+  pools,
+}: Props): JSX.Element => {
+  const sortedPools = getSortedPoolsArray(pools, defaultPoolId);
+  const showOthers = sortedPools.some((pool) => pool[1].allocated_other !== 0);
```
Comment (huwshimi) [inline ui/src/app/kvm/components/StorageColumn/StoragePopover/StoragePopover.tsx:24]: It might be clearer to destructure the pool rather than using the index, which can be a bit obtuse:

```suggestion
  const showOthers = sortedPools.some(([, pool]) => pool.allocated_other !== 0);
```

File: ui/src/app/kvm/components/StorageResources/StorageMeter/StorageMeter.tsx [hunk 3]
```diff
@@ -1,25 +1,24 @@
...
-const StorageMeter = ({ pools }: Props): JSX.Element | null => {
-  const poolsArray = Object.entries<KVMStoragePoolResource>(pools);
-  if (poolsArray.length !== 1) {
+const StorageMeter = ({ defaultPoolId, pools }: Props): JSX.Element | null => {
+  const sortedPools = getSortedPoolsArray(pools);
+  if (sortedPools.length !== 1) {
     return null;
   }
-  const [, pool] = poolsArray[0];
+  const [, pool] = sortedPools[0];
```
Comment (huwshimi) [inline ui/src/app/kvm/components/StorageResources/StorageMeter/StorageMeter.tsx:17]: I know this wasn't added in this branch, but do you remember why we just pick the first pool in the array here? If so, it could be worth leaving as a comment.

**Review by huwshimi — APPROVED** [review]
This looks good, a couple of minor comments.

File: ui/src/app/kvm/components/KVMStorageCards/KVMStorageCards.tsx (hunk 1 above)
Comment (Caleb-Ellis) [reply ui/src/app/kvm/components/KVMStorageCards/KVMStorageCards.tsx:41]: I do yeah, but this is how it was in the original design
