### PR TITLE
fix(ui): prevent long tag names from breaking layout

### LINKED ISSUE #3198: Tag field doesn't handle really long tag names
The tag field doesn't handle long tags, with or without hyphens.

Screen Shot 2021-10-28 at 11 05 59 am

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Added a css util `.u-break-word` and used in a few places that tags might show in order to prevent long tag names from breaking the layout.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to the machine list, select a machine and add some really long tag names
- Check that the tag select field doesn't look completely broken
- Open the details page of the tagged machine and check that the summary page isn't broken at any screen size
- Check the same on the configuration page

## Fixes

Fixes #3198

### CODE REVIEW

File: ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/DetailsCard.tsx [hunk 1]
```diff
@@ -50,10 +50,10 @@ const DetailsCard = ({ machine }: Props): JSX.Element => {
...
         </span>
       </div>
-      {machine.pod ? (
-        <div>
-          <div className="u-text--muted">Host</div>
-          <span data-test="host">
+      <div>
+        <div className="u-text--muted">Host</div>
+        <span data-test="host">
+          {machine.pod ? (
```
Comment (Caleb-Ellis) [inline ui/src/app/machines/views/MachineDetails/MachineSummary/OverviewCard/DetailsCard/DetailsCard.tsx:56]: I've changed the Host section to always render, regardless of whether the machine exists in a host or not (renders "None" instead of a host name). Otherwise it gets a bit spaghetti-y trying to handle responsive layouts with an unknown number of columns.

**Review by huwshimi — APPROVED** [review]
