### PR TITLE
fix(ui): handle undefined machine workload annotations

### LINKED ISSUE #2114: Handle undefined workload_annotations more gracefully
The `master` branch isn't expected to work with older versions of MAAS, but it would be nice if the whole app didn't crash because `workload_annotations` is undefined.

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Improve handling of undefined machine workload annotations
- Drive-by fix for instances tab link

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Set the MAAS_URL to karura (or a different 2.9 MAAS)
- Open the machine list and check that the app doesn't crash
- Check that there is no filter option for "Workloads"
- Go to a machine's details page and check that there is no "Workloads" card

## Fixes

Fixes #2114

### CODE REVIEW

File: ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx [hunk 1]
```diff
@@ -143,7 +143,7 @@ const MachineHeader = ({
                 active: pathname.startsWith(`${urlBase}/instances`),
                 component: Link,
                 label: "Instances",
-                route: `${urlBase}/instances`,
+                to: `${urlBase}/instances`,
```
Comment (Caleb-Ellis) [inline ui/src/app/machines/views/MachineDetails/MachineHeader/MachineHeader.tsx:146]: `route` only works for `LegacyLink` - we actually want the `to` prop here

**Review by squidsoup — APPROVED** [review]
Looks good, thanks @Caleb-Ellis! I think this is a good principal to follow generally, although it really only affects us in development.
