### PR TITLE
fix(ui): standardise shape of node actions

### LINKED ISSUE #3658: Machine list in-table action missing system id
**Describe the bug**
Unable to use in-row actions to commission a machine.

**maas-ui version**
357b86ef

**MAAS version**
3.2.0-alpha1

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to machine list on e.g. bolla
2. Click on Status of one of the machines and click Commission
3. See error "system_id: This field is required"

**Expected behaviour**
Commission form is opened

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser Firefox
 - Version 97.0.1

**Additional context**

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Standardised shape of node action creators (e.g. commission, deploy etc) so that the name of the keys always match what the API expects (`systemId` => `system_id`). I've kept `extra` only in the reducers since it was kind of annoying having to include it in all the action creators.
- Fixed a bug where commissioning didn't work from the in-table action menu

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to the machine list and check that you can commission a machine from the table (from the Status column). It should dispatch an action without any `extra` details - i.e, with defaults.
- Check a few other in-table actions as well as actions from the action menu to see that they still work

## Fixes

Fixes #3658

### CODE REVIEW

File: ui/src/app/store/machine/slice.ts [hunk 1]
```diff
@@ -505,21 +507,6 @@ const machineSlice = createSlice({
...
-          formattedCommissioningScripts = params.commissioningScripts.map(
-            (script) => script.id
-          );
-          if (params.updateFirmware) {
-            formattedCommissioningScripts.push("update_firmware");
-          }
-          if (params.configureHBA) {
-            formattedCommissioningScripts.push("configure_hba");
-          }
-        }
```
Comment (Caleb-Ellis) [inline ui/src/app/store/machine/slice.ts:522]: I decided to move all this logic from the reducer to the commission form, since it's really only useful for that particular form. This way the action creator is more closely aligned to the API and could more easily be used in different contexts.

**Review by huwshimi — APPROVED** [review]
Thanks for doing this clean up!
