### PR TITLE
fix(ui): handle pods with undefined storage pools

### LINKED ISSUE #2081: KVM Page Fails to load with error "An unexpected error has occurred, please try refreshing your browser window."
Bug originally filed by elliotl at https://bugs.launchpad.net/bugs/1912727

MaaS version: 2.9.1

Deployment: 1x Region+Rack Controller + 1x Rack Controller. External PostgreSQL 12 DB.

Issue seems to have came up after the restarting of the main database. All other pages in the web UI load except for the KVM page which has the error "An unexpected error has occurred, please try refreshing your browser window." 

Running a grep to find any reference of the KVM page in logs returns the following: 

grep -rnw /var/snap/ -e "/MAAS/r/kvm"
/var/snap/maas/common/log/regiond.log:275370:2021-01-22 03:34:17 regiond: [info]                                                                                                              My_IP GET /MAAS/r/kvm HTTP/1.1 --> 200 OK (referrer: -; agent: Mozilla                                                                                                             /5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0)
/var/snap/maas/common/log/regiond.log:275374:2021-01-22 03:34:20 regiond: [info]                                                                                                              185.216.144.10 GET /MAAS/r/kvm HTTP/1.1 --> 304 NOT_MODIFIED (referrer: -; agen                                                                                                             t: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.                                                                                                             0)
/var/snap/maas/common/log/regiond.log:296180:2021-01-22 05:36:43 regiond: [info]                                                                                                              My_IP GET /MAAS/r/kvm HTTP/1.1 --> 304 NOT_MODIFIED (referrer: -; agen                                                                                                             t: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.                                                                                                             0)
/var/snap/maas/common/log/regiond.log:296195:2021-01-22 05:38:36 regiond: [info]                                                                                                              My_IP GET /MAAS/r/kvm HTTP/1.1 --> 200 OK (referrer: -; agent: Mozilla                                                                                                             /5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0)
/var/snap/maas/common/log/regiond.log:296222:2021-01-22 05:40:34 regiond: [info]                                                                                                              My_IP GET /MAAS/r/kvm HTTP/1.1 --> 200 OK (referrer: -; agent: Mozilla                                                                                                             /5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0)

Have tried restarting the controllers, the database and clearing any local caches. All other pages seem to load which localizes the problem to how the KVM page in the web ui is different?

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Updated `BasePod` type so that `storage_pools` and `default_storage_pool` are optional, to match the api
- Handle cases where `pod.storage_pools` is undefined

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Check that the KVM list still loads and you can still compose machines
- betterer should pass without needing to update

## Fixes

Related: #2081 

## Launchpad issue

[lp#1912727](https://bugs.launchpad.net/maas/+bug/1912727)

### CODE REVIEW

File: ui/src/app/store/pod/types.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ export type BasePod = Model & {
   power_address: string;
   power_pass?: string;
   owners_count: number;
-  storage_pools: PodStoragePool[];
+  storage_pools?: PodStoragePool[];
```
Comment (huwshimi) [inline ui/src/app/store/pod/types.ts:86]: Might be good to leave a comment about why this might not be defined (it probably always should be?)

**Review by huwshimi — APPROVED** [review]

File: ui/src/app/store/pod/types.ts (hunk 1 above)
Comment (Caleb-Ellis) [reply ui/src/app/store/pod/types.ts:86]: Yep, I think this is really a bug in the websocket handler...
