### PR TITLE
fix(legacy): add undefined object guards to KVM poolOverCapacity function

### LINKED ISSUE #1705: TypeError: Cannot read property 'id' of undefined
https://sentry.is.canonical.com/canonical/maas-ui/issues/11719/?referrer=github_plugin

```
TypeError: Cannot read property 'id' of undefined
  at None (/MAAS/r/1.6f85774a2928f988cdb6.js:35221:1103)
  at Array.find (<anonymous>)
  at ChildScope.KVMStorageDropdownController.$scope.poolOverCapacity (/MAAS/r/1.6f85774a2928f988cdb6.js:35221:1065)
  at fn (/MAAS/r/1.6f85774a2928f988cdb6.js:11536:8)
  at Scope.$digest (/MAAS/r/1.6f85774a2928f988cdb6.js:12439:35)
...
(4 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Added some undefined object guards to KVM `poolOverCapacity` function

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- N/A

## Fixes

Fixes #1705

### CODE REVIEW

File: legacy/src/app/directives/pod-details/kvm_storage_dropdown.js [hunk 1]
```diff
@@ -50,12 +50,20 @@ function KVMStorageDropdownController($scope, $filter) {
...
-    if (compose && compose.obj && pod && pod.storage_pools) {
+    if (
+      compose &&
+      compose.obj &&
+      compose.obj.requests &&
+      pod &&
+      pod.storage_pools &&
+      storage &&
+      storage.pool
+    ) {
```
Comment (huwshimi) [inline legacy/src/app/directives/pod-details/kvm_storage_dropdown.js:61]: Couldn't that just be `if (compose?.obj?.requests && pod?.storage_pools && storage?.pool) {`?

Comment (Caleb-Ellis) [reply legacy/src/app/directives/pod-details/kvm_storage_dropdown.js]: Oh yeah, you're right! This is on the 2.8 branch - I thought that babel wasn't yet transpiling that, but I guess it is.

**Review by huwshimi — APPROVED** [review]
Much?.better?.
