### PR TITLE
fix(ui): fix validation of VLAN DHCP configuration form

### LINKED ISSUE #3629: DHCP configuration form. Configure DHCP button is not enabled
Bug originally filed by troyanov at https://bugs.launchpad.net/bugs/1961594

I was enabling DHCP for the first time.
I navigated to DHCP settings from the VLAN configuration page by clicking "Configure DHCP" button.

Once all fields were filled in, the "Configure DHCP" button was still disabled. After switching radio button to "Relay to another VLAN" and then back to "Provide DHCP from rack controller(s)" the button became enabled.

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Fixed validation of VLAN DHCP configuration form

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to the details page of a VLAN configured with DHCP provided from a rack controller
- Uncheck "MAAS provides DHCP" and then recheck it
- The form should not be disabled

## Fixes

Fixes #3629

### CODE REVIEW

File: ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx [hunk 1]
```diff
@@ -48,12 +48,6 @@ const ConfigureDHCPFields = ({ vlan }: Props): JSX.Element => {
         <FormikField
           label="MAAS provides DHCP"
           name="enableDHCP"
-          onChange={async (e: ChangeEvent) => {
-            await handleChange(e);
-            setFieldValue("primaryRack", "");
-            setFieldValue("relayVLAN", "");
-            setFieldValue("secondaryRack", "");
-          }}
```
Comment (Caleb-Ellis) [inline ui/src/app/subnets/views/VLANDetails/ConfigureDHCP/ConfigureDHCPFields/ConfigureDHCPFields.tsx:56]: I could have updated this to act differently depending on whether `e.target.value` is true or false, but the parent `onSubmit()` handler already handles how to shape the API so it's actually unnecessary to do anything here.
