### PR TITLE
fix(ui): fetch VMs when viewing resources card

### LINKED ISSUE #3105: Look into Resources card not refreshing with VM list

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Fetch VMs when viewing resources card or NUMA card. I'm surprised this bug has lasted this long tbh

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to the resources tab of a KVM and refresh the page
- Check that a loading spinner shows while the machines load, then eventually the dropdown shows.

## Fixes

Fixes #3105

### CODE REVIEW

File: ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx [hunk 1]
```diff
@@ -14,12 +18,18 @@ import type { RootState } from "app/store/root/types";
...
   const pod = useSelector((state: RootState) =>
     podSelectors.getById(state, id)
   );
   const podVMs = useSelector((state: RootState) =>
     podSelectors.getVMs(state, id)
   );
+  const machinesLoading = useSelector(machineSelectors.loading);
+
+  useEffect(() => {
+    dispatch(machineActions.fetch());
```
Comment (huwshimi) [inline ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx:31]: We should file a bug about being able to fetch just the machines for a KVM so that we don't have to load all the machines in the MAAS.

**Review by huwshimi — APPROVED** [review]

File: ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx (hunk 1 above)
Comment (Caleb-Ellis) [reply ui/src/app/kvm/components/KVMResourcesCard/KVMResourcesCard.tsx:31]: Done https://bugs.launchpad.net/maas/+bug/1950108
