### PR TITLE
Fix NUMA card styling errors.

### LINKED ISSUE #964: NUMA nodes accordion overflowing

### LINKED ISSUE #965: NUMA nodes not rounding values

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done
- Converted NUMA core list into core ranges (e.g. "0, 1, 2, 3, 5, 6, 8" => "0-3, 5-6, 8").
- Rounded NUMA memory values to four significant figures.
- Improved null/zero cases for NUMA values, e.g. "0" => "0 B", "0 disk" => "0 disks".

## QA
- Open `node_details.js` and replace lines 473-479 with [this pastebin](https://pastebin.canonical.com/p/HBSn4GYYbm/).
- Go to the details page of any machine which now has fake data for 4 NUMA nodes.
- Check that the NUMA card matches the [design](https://camo.githubusercontent.com/8d85d6a881645a4fd7cbad80eb42eb16a8f53ee5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3561663937363732346235383036626332626433303836302f61633134303163382d313464632d343031662d613839332d626634326237306538613361)
- Check that the null cases read better.

## Fixes
Fixes #964 
Fixes #965
Fixes canonical-web-and-design/MAAS-design#895

### Collapsed
Screenshot_2020-04-16 alert-roughy maas bolla MAAS

### Expanded
Screenshot_2020-04-16 alert-roughy maas bolla MAAS(1)

### CODE REVIEW

File: legacy/src/app/controllers/node_details.js [hunk 1]
```diff
@@ -6,6 +6,38 @@
...
+  for (let i = 0; i < array.length; i++) {
+    rangeStart = array[i];
+    rangeEnd = rangeStart;
+    // Keep incrementing rangeEnd while its a consecutive number.
+    while (parseInt(array[i + 1]) - parseInt(array[i]) === 1) {
+      rangeEnd = parseInt(array[i + 1]);
+      i++;
+    }
+    ranges.push(
+      rangeStart === rangeEnd ? `${rangeStart}` : `${rangeStart}-${rangeEnd}`
```
Comment (huwshimi) [inline legacy/src/app/controllers/node_details.js:33]: ```... ? `${rangeStart}` : ...``` could be `... ? rangeStart : ...` or is that to convert it to a string?

File: legacy/src/app/controllers/node_details.js [hunk 2]
```diff
@@ -6,6 +6,38 @@
...
+const formatNumaMemory = (mib) => {
+  if (mib >= 1024) {
+    return `${Number((mib / 1024).toPrecision(4)).toString()} GiB`;
+  }
+  return `${Number(mib.toPrecision(4)).toString()} MiB`;
+};
+
+// Convert array of numbers into range strings,
+// e.g [0, 1, 2, 4, 6, 7] => ["0-2", "4", "6-7"]
+const getRanges = (array) => {
```
Comment (huwshimi) [inline legacy/src/app/controllers/node_details.js:19]: Is the provided array always sorted low to high?

File: legacy/src/app/controllers/node_details.js [hunk 3]
```diff
@@ -6,6 +6,38 @@
...
+  const ranges = [];
+  let rangeStart;
+  let rangeEnd;
+
+  for (let i = 0; i < array.length; i++) {
+    rangeStart = array[i];
+    rangeEnd = rangeStart;
+    // Keep incrementing rangeEnd while its a consecutive number.
```
[the remark this answers is not in the document]
Comment (Caleb-Ellis) [reply legacy/src/app/controllers/node_details.js]: how could i have done this

File: legacy/src/app/controllers/node_details.js (hunk 1 above)
Comment (Caleb-Ellis) [reply legacy/src/app/controllers/node_details.js:34]: Yeah I've forced them all to be strings so you don't end up with mixed types in the array, like `[0, "1-2", 3, "4-10"]` etc.

File: legacy/src/app/controllers/node_details.js (hunk 2 above)
Comment (Caleb-Ellis) [reply legacy/src/app/controllers/node_details.js]: I've assumed yes just because that's how the data's come in like that every time, but you're right I should sort it first lest we end up in an infinite loop.
